{% set name = "benchmark" %}
{% set version = "1.5.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/google/benchmark/archive/v{{ version }}.tar.gz
  sha256: 23082937d1663a53b90cb5b61df4bcc312f6dee7018da78ba00dd6bd669dfef2

build:
  number: 2

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - test -f $PREFIX/include/benchmark/benchmark.h  # [unix]
    - if not exist %LIBRARY_INC%\\benchmark\\benchmark.h exit 1  # [win]
    - test ! -f $PREFIX/lib/libbenchmark.a  # [unix]
    - test ! -f $PREFIX/lib/libbenchmark_main.a  # [unix]
    - test -f $PREFIX/lib/libbenchmark${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libbenchmark_main${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\lib\\benchmark.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\benchmark_main.lib exit 1  # [win]

about:
  home: https://github.com/google/benchmark
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A microbenchmark support library

extra:
  recipe-maintainers:
    - xhochy
    - wesm
    - pitrou
    - kszucs
    - saraedum
